### ISSUE TITLE
Only first connection works

### ISSUE THREAD

**Issue by hansnull** [peterlewis/wg-easy#64]
**Describe the bug**
Only the first connection works, all other ones do not work

**To Reproduce**
use the latest tag (docker)

**Expected behavior**
should just work

**Additional context**
Compared with tag 11 which just works

**Comment by peterlewis** [comment]
Hi @hansnull! Sorry to hear you're having issues and I am very sorry for the late reply. I had not set up my alerting correctly after enabling issues. I have been able to reproduce the issue. Please could I ask you to switch over to `nightly` whilst I push a fix?

**Comment by peterlewis** [comment]
Hi @hansnull. This issue is now fixed with v12 release. Thanks!
