### ISSUE TITLE
No connection with latest v12

### ISSUE THREAD

**Issue by redstripes89** [peterlewis/wg-easy#71]
**Describe the bug**
After updating to the latest version v12 none of my clients can connect anymore. Neither my iPhone nor my Windows 11 PC are able to setup a connection. After switching back to v11, everything just works as expected. Clients seem to send some bytes, but don't retrieve any. 

**To Reproduce**
1. Update to v12
2. Try to connect any client

**Expected behavior**
Client should be connected

**Additional context**

**Comment by pheiduck** [comment]
I know the problem that only packets are sent, but none are received.
In the client app, 2 or 3 reconnections are required.
So please try that.

**Comment by pheiduck** [comment]
But I have not yet found out where the problem lies `docker log` does not return any errors

**Comment by pheiduck** [comment]
There a good news: @peterlewis and I am working now on the upstream project: https://github.com/wg-easy/wg-easy
Feel free to add your issue [here](https://github.com/wg-easy/wg-easy/issues)

**Comment by peterlewis** [comment]
Thank you for raising @redstripes89. As @pheiduck says, we're moving development upstream. If I could ask you to please test the latest nightly release (`ghcr.io/wg-easy/wg-easy:development`) and, if you are experiencing continued issues, please may you [raise an issue on the upstream repository](https://github.com/wg-easy/wg-easy/issues)?

This fork will be archived once the rebase hits production, upstream.

Thanks and sorry you're experiencing an issue. I hope we can resolve it quickly!

**Comment by peterlewis** [comment]
Closing in favour of https://github.com/wg-easy/wg-easy/issues/694.
